language: python
sudo: false

python:
- 3.6

install:
- travis_retry pip install -r requirements-dev.txt
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
  - py.test --pyargs nitime --cov-report term-missing --cov=nitime --verbose

after_success:
- coveralls
